# Generated by Django 5.1.3 on 2024-11-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_schema',
            fields=[
                ('updatedAt', models.TimeField(auto_created=True)),
                ('createdAt', models.TimeField(auto_created=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('shortCode', models.CharField(max_length=100)),
            ],
        ),
    ]
