# Generated by Django 5.1.3 on 2024-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_schema',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='shortCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='url',
            field=models.URLField(),
        ),
    ]
