# Generated by Django 5.1.3 on 2024-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_schema_createdat_alter_url_schema_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_schema',
            name='createdAt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='updatedAt',
            field=models.CharField(max_length=100),
        ),
    ]
