# Generated by Django 5.1.3 on 2024-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_remove_url_schema_id_alter_url_schema_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_schema',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url_schema',
            name='url',
            field=models.URLField(),
        ),
    ]
