# Generated by Django 5.1.3 on 2024-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_url_schema_id_alter_url_schema_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_schema',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
